### ISSUE TITLE
请问一下，这个如何使用芽，

### ISSUE THREAD

**Issue by SmallRedSister** [DeSireFire/animeTrackerList#1]
萌新，不太这些骚操作，望指导一些

**Comment by DeSireFire** [comment]
很抱歉，我才刚刚看见。
使用方法具体，大致分为两大类：
1. 自己拼接磁性链接的tracker
2. 使用的BT下载工具
法一：

磁链格式：magnet:?xt=urn:btih:{ 下载资源的hash值 }&dn={ 资源名称，此处可留空 }&tr={ 资源跟踪器（tracker） }&tr={ 资源跟踪器（tracker） }.....

使用项目中 AT_best.txt 等等 文本url中的 tracker 来构造自己的磁性链接。
举例:

打开：https://raw.githubusercontent.com/DeSireFire/animeTrackerList/master/AT_best.txt，得到以下跟踪器：
http://exodus.desync.com/announce
http://mkfs.ru/announce
https://1337.abcvg.info/announce
http://0123456789nonexistent.com/announce
http://tracker.kisssub.org/announce
http://pt.lax.mx/announce
http://tr.bangumi.moe/announce
http://tracker.acgnx.se/announce
http://tracker.tfile.co/announce
https://open.kickasstracker.com/announce
http://tracker.tfile.me/announce.php
http://tracker.trackerfix.com/announce
http://ehtracker.org/1226599/1080494xo5eXcwFOBq/announce
http://peersteers.org/announce
http://tracker.btcake.com/announce
https://tracker.fastdownload.xyz/announce
http://ehtracker.org/1113709/announce
http://t1.pow7.com/announce
http://tracker.baka-sub.cf/announce
http://tracker.bittorrent.am/announce.php
http://atrack.pow7.com/announce
http://torrent.nwps.ws/announce
http://tracker.shuim.net/announce.php
http://denis.stalker.h3q.com/announce.php
http://tracker.tfile.me/announce
根据磁性链接的格式，构造出新磁性链接即可
magnet:?xt=urn:btih:Z7ZDIYEBZHIKE7MOZJQKLYVHWX5SEKMH&dn=喵喵喵&tr=http://exodus.desync.com/announce&tr=http://mkfs.ru/announce&tr=https://1337.abcvg.info/announce&tr=....等等等（多个tacker,即&tr={ 资源跟踪器（tracker） }，无上限..）

法二：
得看具体是使用什么BT下载器，以Bitcomet为例：

在Bitcomet软件里添加下载任务时弹出的任务属性里（也可以右键选择属性），选择“高级设置”选项卡，在服务器列表里添加Tracker服务器地址。

将https://raw.githubusercontent.com/DeSireFire/animeTrackerList/master/AT_all.txt 等 文件url里的内容粘贴上去即可。

![image](https://user-images.githubusercontent.com/18726905/60825706-dc290c00-a1de-11e9-9098-4cb1ccb42f19.png)
