### ISSUE TITLE
遇到了问题

### ISSUE THREAD

**Issue by dora-world** [DeSireFire/animeTrackerList#11]
Failed to decode tracker response.
请问这是怎么回事啊

**Comment by DeSireFire** [comment]
> Failed to decode tracker response.
> 请问这是怎么回事啊

使用得什么BT工具？使用得是哪个trackers链接？

**Comment by dora-world** [comment]
链接基本都这样 比特彗星 谢谢

**Comment by DeSireFire** [comment]
> 链接基本都这样 比特彗星 谢谢

装bitcomet装了好久。
Failed to decode tracker response.
个人感觉是你所处的网络环境链接github不畅。
我这边测试一下，如果你是在国内用的话，建议使用缓存加速的接口。
```text
[RAW]
https://at.raxianch.moe/?type=AT-best
https://at.raxianch.moe/?type=AT-all
https://at.raxianch.moe/?type=AT-all-udp
https://at.raxianch.moe/?type=AT-all-http
https://at.raxianch.moe/?type=AT-all-https
https://at.raxianch.moe/?type=AT-all-ws
https://at.raxianch.moe/?type=AT-best-ip
https://at.raxianch.moe/?type=AT-all-ip
```
这是我用bitcomet测试的图片。
![image](https://user-images.githubusercontent.com/18726905/103099589-147a0f80-464a-11eb-904a-941f3c3b77ad.png)
trackers更新没问题。
![image](https://user-images.githubusercontent.com/18726905/103099612-2d82c080-464a-11eb-9a56-61787269f1a8.png)
下载情况也OK。

**Comment by dora-world** [comment]
感谢我再试试
