### ISSUE TITLE
announce.php大部分是Private Tracker

### ISSUE THREAD

**Issue by Latezly** [DeSireFire/animeTrackerList#14]
https://github.com/DeSireFire/animeTrackerList/blob/3d26bae9b146207d34398ebdb56c193b3a6a2fb3/AT_all.txt#L5
这种tracker一般是在私有pt站里加上自己的秘钥才能使用，公共bt站用不了

**Comment by DeSireFire** [comment]
> https://github.com/DeSireFire/animeTrackerList/blob/3d26bae9b146207d34398ebdb56c193b3a6a2fb3/AT_all.txt#L5
> 
> 
> 这种tracker一般是在私有pt站里加上自己的秘钥才能使用，公共bt站用不了

可以更具体的描述一下pt的url特征吗？如果能提供筛选思路更好，感谢！之后会根据情况来开发优化

all.txt一般是往全的方向去存。

虽然没有密钥的时候PT-Tracker是无效的，但是添加到下载器中不会影响到使用。

**Comment by Latezly** [comment]
>可以更具体的描述一下pt的url特征吗？如果能提供筛选思路更好，感谢！之后会根据情况来开发优化

以我上面发的这个tracker url为例，他的完整版是
`https://tracker.m-team.cc/announce.php?passkey=abcdefg123456321654qqssddff`
后面的passkey里为每个人的专属key，通常为32位英文字母+数字，根据用户的BT程序客户端每次向tracker服务器汇报的时候会记录当前key所对应用户的下载量和上传量，其他的PTtracker也大同小异。

一般情况下仅携带`https://tracker.domain.com:443/announce.php`→**announce.php**这种php写的tracker绝大多数都是PTtracker,但却没有秘钥参数的话，tracker服务器会直接拒绝响应，所以说直接添加**没有key**的PTtracker是完全没有意义的。

另外即使是同一个种子，完全相同的内容，但如果一个是公开种子，一个是私有种子的话hash也会完全不同
（具体的区别可以用[种子编辑器](https://github.com/torrent-file-editor/torrent-file-editor)查看）
在`tracker`和`BT软件`眼里会把他视为两个完全不同的种子，所以说在同一个种子里同时添加PTtracker和BTtracker也是没法共用的

>all.txt一般是往全的方向去存。
>虽然没有密钥的时候PT-Tracker是无效的，但是添加到下载器中不会影响到使用。

另外我之前有印象在qbittorrent的issues里有看到，qbittorrent并不会同时向同一个种子里所有的tracker汇报，（貌似最多是15个？），其余的tracker都会处于未工作状态，其他的bt客户端暂时没有测试过；

如果说其他bt客户端是能够直接全部汇报的话，同一瞬间向所有的tracker发送一大堆请求，emmmmmmm你懂吧  感觉不是很那啥
所以一定程度上tracker并不是越多越好

**Comment by DeSireFire** [comment]
> > 可以更具体的描述一下pt的url特征吗？如果能提供筛选思路更好，感谢！之后会根据情况来开发优化
> 
> 以我上面发的这个tracker url为例，他的完整版是
> `https://tracker.m-team.cc/announce.php?passkey=abcdefg123456321654qqssddff`
> 后面的passkey里为每个人的专属key，通常为32位英文字母+数字，根据用户的BT程序客户端每次向tracker服务器汇报的时候会记录当前key所对应用户的下载量和上传量，其他的PTtracker也大同小异。
> 
> 一般情况下仅携带`https://tracker.domain.com:443/announce.php`→**announce.php**这种php写的tracker绝大多数都是PTtracker,但却没有秘钥参数的话，tracker服务器会直接拒绝响应，所以说直接添加**没有key**的PTtracker是完全没有意义的。
> 
> 另外即使是同一个种子，完全相同的内容，但如果一个是公开种子，一个是私有种子的话hash也会完全不同
> （具体的区别可以用[种子编辑器](https://github.com/torrent-file-editor/torrent-file-editor)查看）
> 在`tracker`和`BT软件`眼里会把他视为两个完全不同的种子，所以说在同一个种子里同时添加PTtracker和BTtracker也是没法共用的
> 
> > all.txt一般是往全的方向去存。
> > 虽然没有密钥的时候PT-Tracker是无效的，但是添加到下载器中不会影响到使用。
> 
> 另外我之前有印象在qbittorrent的issues里有看到，qbittorrent并不会同时向同一个种子里所有的tracker汇报，（貌似最多是15个？），其余的tracker都会处于未工作状态，其他的bt客户端暂时没有测试过；
> 
> 如果说其他bt客户端是能够直接全部汇报的话，同一瞬间向所有的tracker发送一大堆请求，emmmmmmm你懂吧 感觉不是很那啥
> 所以一定程度上tracker并不是越多越好

总结一下，
tracker的URL里存在announce.php的大部分为PT地址；
而如果 Pt 的 url没有key参数的，都可以视为是无效tracker是吗?

**Comment by Latezly** [comment]
> 总结一下，
tracker的URL里存在announce.php的大部分为PT地址；
而如果 Pt 的 url没有key参数的，都可以视为是无效tracker是吗?

是的

**Comment by zhongfly** [comment]
这个问题到现在也还没有解决，至少可以建一个排除列表，全指望自动也不太现实的
今天依然有这2个pt trcker在best列表里

https://github.com/DeSireFire/animeTrackerList/blob/02b0802ce5695783d3e8036a9dc08f594e7e018e/AT_best.txt#L10-L13
