### ISSUE TITLE
你好，我想向你请教一下ftplib，不知道怎么联系你啊

### ISSUE THREAD

**Issue by Broad-sky** [DeSireFire/animeTrackerList#2]

**Comment by DeSireFire** [comment]
我才刚刚看到issues，自从爱信息图床因为不可抗力关站以后，我就没有再弄过ftplib了。
我印象中FTP的问题是比较玄学的，得看情况分析了。
想想也有一年了吧，ftplib也忘了差不多了，哈哈哈哈

**Comment by Broad-sky** [comment]
哈哈，太尴尬了，谢谢你的回复，我的问题已经解决了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "RaXianch"<notifications@github.com&gt;; 
发送时间: 2019年9月30日(星期一) 上午10:11
收件人: "DeSireFire/animeTrackerList"<animeTrackerList@noreply.github.com&gt;; 
抄送: "沈平生"<2440384985@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [DeSireFire/animeTrackerList] 你好，我想向你请教一下ftplib，不知道怎么联系你啊，我的QQ1745379960 (#2)




我才刚刚看到issues，自从爱信息图床因为不可抗力关站以后，我就没有再弄过ftplib了。
 我印象中FTP的问题是比较玄学的，得看情况分析了。
 想想也有一年了吧，ftplib也忘了差不多了，哈哈哈哈

**Comment by DeSireFire** [comment]
> 哈哈，太尴尬了，谢谢你的回复，我的问题已经解决了
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "RaXianch"<notifications@github.com&gt;; 发送时间: 2019年9月30日(星期一) 上午10:11 收件人: "DeSireFire/animeTrackerList"<animeTrackerList@noreply.github.com&gt;; 抄送: "沈平生"<2440384985@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [DeSireFire/animeTrackerList] 你好，我想向你请教一下ftplib，不知道怎么联系你啊，我的QQ1745379960 (#2) 我才刚刚看到issues，自从爱信息图床因为不可抗力关站以后，我就没有再弄过ftplib了。 我印象中FTP的问题是比较玄学的，得看情况分析了。 想想也有一年了吧，ftplib也忘了差不多了，哈哈哈哈 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

我很好奇具体是什么原因出得问题呢？

**Comment by Broad-sky** [comment]
服务器放火墙的问题，已经解决了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "RaXianch"<notifications@github.com&gt;; 
发送时间: 2019年9月30日(星期一) 上午10:28
收件人: "DeSireFire/animeTrackerList"<animeTrackerList@noreply.github.com&gt;; 
抄送: "沈平生"<2440384985@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [DeSireFire/animeTrackerList] 你好，我想向你请教一下ftplib，不知道怎么联系你啊，我的QQ1745379960 (#2)



 
哈哈，太尴尬了，谢谢你的回复，我的问题已经解决了
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "RaXianch"<notifications@github.com&gt;; 发送时间: 2019年9月30日(星期一) 上午10:11 收件人: "DeSireFire/animeTrackerList"<animeTrackerList@noreply.github.com&gt;; 抄送: "沈平生"<2440384985@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [DeSireFire/animeTrackerList] 你好，我想向你请教一下ftplib，不知道怎么联系你啊，我的QQ1745379960 (#2) 我才刚刚看到issues，自从爱信息图床因为不可抗力关站以后，我就没有再弄过ftplib了。 我印象中FTP的问题是比较玄学的，得看情况分析了。 想想也有一年了吧，ftplib也忘了差不多了，哈哈哈哈 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.
  
我很好奇具体是什么原因出得问题呢？
