### ISSUE TITLE
加了tracker无速度

### ISSUE THREAD

**Issue by googidaddy** [DeSireFire/animeTrackerList#24]
新人报道~

`magnet:?xt=urn:btih:909a5b32378dce7e44fff5f435c09a7e25df926a&dn=%5bDymy%5d%5bNanatsu%20no%20Taizai%20The%20Seven%20Deadly%20Sins%5d%5b01-24%5d%5bBIG5%5d%5b1280X720%5d`

七大罪的磁链。但是tracker 好多permiss denied和bad gateway

**Comment by DeSireFire** [comment]
> 新人报道~
> 
> `magnet:?xt=urn:btih:909a5b32378dce7e44fff5f435c09a7e25df926a&dn=%5bDymy%5d%5bNanatsu%20no%20Taizai%20The%20Seven%20Deadly%20Sins%5d%5b01-24%5d%5bBIG5%5d%5b1280X720%5d`
> 
> 七大罪的磁链。但是tracker 好多permiss denied和bad gateway

感谢反馈和提供具体的磁链案例，我日后测试一下看看具体的原因。再看下一步怎么处理
