### ISSUE TITLE
Delete tracker request

### ISSUE THREAD

**Issue by HanadaLee** [DeSireFire/animeTrackerList#27]
Hi animeTrackerList Maintainer,

We are Tamers Union subtitle group, the owner of  http://tracker.tamersunion.org/.
In fact, we only want to use the tracker for the torrents we publish ourselves, but we don't have a good way to limit it, so public torrents can also access our tracker, but our server can't bear it due to the excessive traffic, So hope to remove our tracker from your project, thank you.
 
Our Tracker is 
https://tracker.tamersunion.org:443/announce

https://tracker.tamersunion.org/announce
If possible, blacklist it from being added to your project.

**Comment by lslqtz** [comment]
You should use info_hash white list to block the HTTP request once and for all.

**Comment by DeSireFire** [comment]
> Hi animeTrackerList Maintainer,
> 
> We are Tamers Union subtitle group, the owner of http://tracker.tamersunion.org/. In fact, we only want to use the tracker for the torrents we publish ourselves, but we don't have a good way to limit it, so public torrents can also access our tracker, but our server can't bear it due to the excessive traffic, So hope to remove our tracker from your project, thank you.
> 
> Our Tracker is https://tracker.tamersunion.org:443/announce
> 
> https://tracker.tamersunion.org/announce If possible, blacklist it from being added to your project.

This is the response from Google Translate:

Sorry for replying to your message so late.
I will add your trakcer address to the filter to remove them from the list.

**Comment by HanadaLee** [comment]
> > Hi animeTrackerList Maintainer,
> > We are Tamers Union subtitle group, the owner of http://tracker.tamersunion.org/. In fact, we only want to use the tracker for the torrents we publish ourselves, but we don't have a good way to limit it, so public torrents can also access our tracker, but our server can't bear it due to the excessive traffic, So hope to remove our tracker from your project, thank you.
> > Our Tracker is https://tracker.tamersunion.org:443/announce
> > https://tracker.tamersunion.org/announce If possible, blacklist it from being added to your project.
> 
> This is the response from Google Translate:
> 
> Sorry for replying to your message so late. I will add your trakcer address to the filter to remove them from the list.

It doesn't matter. We have prepared a more sufficient load cluster for it. There is no need to do anything at the moment. I just forgot to close this issue.

顺带，其实没必要机翻🤣
