### ISSUE TITLE
请教tracker检测的方法

### ISSUE THREAD

**Issue by aclihub** [DeSireFire/animeTrackerList#3]
请教tracker检测的方法，看源代码是python，求大神指导

**Comment by aclihub** [comment]
算了吧当我没说

**Comment by DeSireFire** [comment]
呃....很抱歉..我才刚刚发现原来还有这个issue.
那会儿年底干活赶工，没能看到。
既然看到了，我肯定会回复你的，23333
这个检测的话，需要使用python的socket.
用它来测试tracker服务器的网路状况.
死的tracker或者链接特别不畅的traceker基本没法用咯。
网上应该都能搜索得到。
