### ISSUE TITLE
能不能支持Aria2

### ISSUE THREAD

**Issue by ccicnce113424** [DeSireFire/animeTrackerList#4]
我一般用Aria2，Tracker是用逗号隔开的，能不能增加Aria2版本的

**Comment by DeSireFire** [comment]
@ccicnce113424 抱歉，刚刚看到消息。
周末我找时间增加一下这个版本

**Comment by ccicnce113424** [comment]
只不过是格式的问题，你可以把空行替换成逗号

**Comment by DeSireFire** [comment]
哈哈哈，主要是这个项目也有一段时间了，问题其实也观察的差不多了，想找时间做个重构。
这个也会放在更新内容里面。

**Comment by DeSireFire** [comment]
> 只不过是格式的问题，你可以把空行替换成逗号

已经添加逗号分隔的支持，用于aira2,我手上没有测试aria2的环境，你看看有没有什么问题。
没问题的话，回复一下，我就关闭此条了。
