### ISSUE TITLE
网站+网络

### ISSUE THREAD

**Issue by yangtzech** [DeSireFire/animeTrackerList#5]
作者你好，能不能说明下已经添加了tracker的网站？还有就是，github访问速度有时候很慢，可能会无法更新，作者可以考虑在码云上建立一个仓库吗？

**Comment by DeSireFire** [comment]
Q:能不能说明下已经添加了tracker的网站？
A:我有点看懵了，说明文档上面有写噢。除了划了删除线的。如果你指的是其他的tracker网站，欢迎提出。我会加入的。

Q:可以考虑在码云上建立一个仓库吗？
A：暂时还没有这个想法，主要看需求。关于github访问慢的解决办法，我会想办法用其他办法加速来解决，会作为之后的升级。

**Comment by yangtzech** [comment]
> Q:能不能说明下已经添加了tracker的网站？
> A:我有点看懵了，说明文档上面有写噢。除了划了删除线的。如果你指的是其他的tracker网站，欢迎提出。我会加入的。
> 
> Q:可以考虑在码云上建立一个仓库吗？
> A：暂时还没有这个想法，主要看需求。关于github访问慢的解决办法，我会想办法用其他办法加速来解决，会作为之后的升级。



陆续支持网站A,B,C感觉是将要做还没有做。
所以是已经支持了前六个网站，还没支持http://www.kisssub.org？

**Comment by DeSireFire** [comment]
嗯，是的。

**Comment by DeSireFire** [comment]
> > Q:能不能说明下已经添加了tracker的网站？
> > A:我有点看懵了，说明文档上面有写噢。除了划了删除线的。如果你指的是其他的tracker网站，欢迎提出。我会加入的。
> > Q:可以考虑在码云上建立一个仓库吗？
> > A：暂时还没有这个想法，主要看需求。关于github访问慢的解决办法，我会想办法用其他办法加速来解决，会作为之后的升级。
> 
> 陆续支持网站A,B,C感觉是将要做还没有做。
> 所以是已经支持了前六个网站，还没支持[http://www.kisssub.org？](http://www.kisssub.org%EF%BC%9F)

嗯，是的

**Comment by yangtzech** [comment]
> > > Q:能不能说明下已经添加了tracker的网站？
> > > A:我有点看懵了，说明文档上面有写噢。除了划了删除线的。如果你指的是其他的tracker网站，欢迎提出。我会加入的。
> > > Q:可以考虑在码云上建立一个仓库吗？
> > > A：暂时还没有这个想法，主要看需求。关于github访问慢的解决办法，我会想办法用其他办法加速来解决，会作为之后的升级。
> > 
> > 
> > 陆续支持网站A,B,C感觉是将要做还没有做。
> > 所以是已经支持了前六个网站，还没支持[http://www.kisssub.org？](http://www.kisssub.org%EF%BC%9F)
> 
> 嗯，是的

好的，谢谢

**Comment by DeSireFire** [comment]
> > > > Q:能不能说明下已经添加了tracker的网站？
> > > > A:我有点看懵了，说明文档上面有写噢。除了划了删除线的。如果你指的是其他的tracker网站，欢迎提出。我会加入的。
> > > > Q:可以考虑在码云上建立一个仓库吗？
> > > > A：暂时还没有这个想法，主要看需求。关于github访问慢的解决办法，我会想办法用其他办法加速来解决，会作为之后的升级。
> > > 
> > > 
> > > 陆续支持网站A,B,C感觉是将要做还没有做。
> > > 所以是已经支持了前六个网站，还没支持[http://www.kisssub.org？](http://www.kisssub.org%EF%BC%9F)
> > 
> > 
> > 嗯，是的
> 
> 好的，谢谢

你是用在什么项目上吗？

**Comment by yangtzech** [comment]
> > > > > Q:能不能说明下已经添加了tracker的网站？
> > > > > A:我有点看懵了，说明文档上面有写噢。除了划了删除线的。如果你指的是其他的tracker网站，欢迎提出。我会加入的。
> > > > > Q:可以考虑在码云上建立一个仓库吗？
> > > > > A：暂时还没有这个想法，主要看需求。关于github访问慢的解决办法，我会想办法用其他办法加速来解决，会作为之后的升级。
> > > > 
> > > > 
> > > > 陆续支持网站A,B,C感觉是将要做还没有做。
> > > > 所以是已经支持了前六个网站，还没支持[http://www.kisssub.org？](http://www.kisssub.org%EF%BC%9F)
> > > 
> > > 
> > > 嗯，是的
> > 
> > 
> > 好的，谢谢
> 
> 你是用在什么项目上吗？

没。。就是下动漫

**Comment by DeSireFire** [comment]
> > > > > > Q:能不能说明下已经添加了tracker的网站？
> > > > > > A:我有点看懵了，说明文档上面有写噢。除了划了删除线的。如果你指的是其他的tracker网站，欢迎提出。我会加入的。
> > > > > > Q:可以考虑在码云上建立一个仓库吗？
> > > > > > A：暂时还没有这个想法，主要看需求。关于github访问慢的解决办法，我会想办法用其他办法加速来解决，会作为之后的升级。
> > > > > 
> > > > > 
> > > > > 陆续支持网站A,B,C感觉是将要做还没有做。
> > > > > 所以是已经支持了前六个网站，还没支持[http://www.kisssub.org？](http://www.kisssub.org%EF%BC%9F)
> > > > 
> > > > 
> > > > 嗯，是的
> > > 
> > > 
> > > 好的，谢谢
> > 
> > 
> > 你是用在什么项目上吗？
> 
> 没。。就是下动漫

哈哈哈，但愿能帮到你，使用愉快！
