### ISSUE TITLE
all list中出现几个排版以及格式错误

### ISSUE THREAD

**Issue by EA-DICE** [DeSireFire/animeTrackerList#6]
AT_all.txt#L77 端口前面缺少冒号
AT_all.txt#L85 非 Tracker 内容
AT_all.txt#L113 端口前面应该是冒号而不是点

**Comment by EA-DICE** [comment]
以上为不完全统计

**Comment by EA-DICE** [comment]
还有一个小小的错误，https://github.com/DeSireFire/animeTrackerList 标签中“aira2”似乎拼写错误，应为“aria2”

**Comment by DeSireFire** [comment]
感谢朋友这么详细的反馈，应该已经解决了。看看是否还有此类问题，是我没有发现的

**Comment by EA-DICE** [comment]
tag可以考虑更正一下

**Comment by DeSireFire** [comment]
Done,

> 还有一个小小的错误，https://github.com/DeSireFire/animeTrackerList标签中“ aira2”似乎拼写错误，应为“ aria2”

Done,已经更正，感谢！

如果觉得都OK了，就由你来关闭问题吧

**Comment by EA-DICE** [comment]
好的，感谢。如还有问题我会积极汇报的
