### ISSUE TITLE
添加了这个trackerlist之后，端口和DHT都是绿灯比特彗星依然没速度

### ISSUE THREAD

**Issue by MinaseInori233** [DeSireFire/animeTrackerList#8]
种子是7年前的魔法少女小圆剧场版，应该不算很冷很死的种子吧？
吸血雷倒是有速度...

**Comment by DeSireFire** [comment]
磁链发来看看。

**Comment by MinaseInori233** [comment]
> 磁链发来看看。


[FCFDD1AA9D521B10761DDBADF72F998CD085F9CF.zip](https://github.com/DeSireFire/animeTrackerList/files/4851785/FCFDD1AA9D521B10761DDBADF72F998CD085F9CF.zip)

就是这个了

**Comment by DeSireFire** [comment]
![image](https://user-images.githubusercontent.com/18726905/86216558-cca19080-bbb0-11ea-8f04-f0c2df7064c9.png)
使用aria2测试，然后就去睡觉了，速度还可以啊。
资源在tracker上是有的，但是可能是你在的区域链接tracker不畅。
以下是我用的tracker:
&tr=http%3A%2F%2F104.238.198.186%3A8000%2Fannounce&tr=udp%3A%2F%2F104.238.198.186%3A8000%2Fannounce&tr=http%3A%2F%2Ftracker.openbittorrent.com%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker3.itzmx.com%3A6961%2Fannounce&tr=http%3A%2F%2Ftracker4.itzmx.com%3A2710%2Fannounce&tr=http%3A%2F%2Ftracker.publicbt.com%3A80%2Fannounce&tr=http%3A%2F%2Ftracker.prq.to%2Fannounce&tr=http%3A%2F%2Fopen.acgtracker.com%3A1096%2Fannounce&tr=https%3A%2F%2Ft-115.rhcloud.com%2Fonly_for_ylbud&tr=http%3A%2F%2Ftracker1.itzmx.com%3A8080%2Fannounce&tr=http%3A%2F%2Ftracker2.itzmx.com%3A6961%2Fannounce&tr=udp%3A%2F%2Ftracker1.itzmx.com%3A8080%2Fannounce&tr=udp%3A%2F%2Ftracker2.itzmx.com%3A6961%2Fannounce&tr=udp%3A%2F%2Ftracker3.itzmx.com%3A6961%2Fannounce&tr=udp%3A%2F%2Ftracker4.itzmx.com%3A2710%2Fannounce&tr=http%3A%2F%2Ftracker.acgnx.se%2Fannounce
