### ISSUE TITLE
Bug Report - Wrong tracker server!!!"udp://tracker.leechers-"

### ISSUE THREAD

**Issue by AceBee007** [DeSireFire/animeTrackerList#9]
Auto Push at 2020-07-03 12:11:40

AT_best.txt
[AT_best.txt](https://github.com/DeSireFire/animeTrackerList/blob/master/AT_best.txt)

at line 7
```
udp://bt.dy20188.com/announce
udp://tracker.leechers-
udp://tracker.acgnx.se/announce
```

I guess it should be `udp://tracker.leechers-paradise.org:6969/announce`.

Please fix this bug

**Comment by DeSireFire** [comment]
okay,Thanks for your feedback.
This seems to be wrong.
Let me have a look.

**Comment by DeSireFire** [comment]
I have fixed the bug.
Thanks for your feedback again.
